### ISSUE TITLE
Error: electron manager could not start all workers..

### ISSUE THREAD

**Issue by lambda-zhang** [bjrmatos/electron-workers#146]
how could i use electron-workers？
following  README.md， use ipc mode， i got this：

{ Error: electron manager could not start all workers..
    at startHandler (/home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/ElectronManager.js:137:37)
    at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/ElectronWorker.js:316:20
    at ElectronWorker.statusHandler (/home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/ElectronWorker.js:349:16)
    at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/checkIpcStatus.js:39:9
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  workerErrors: 
   [ Error: message could not be sent to electron process
         at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/checkIpcStatus.js:39:12
         at _combinedTickCallback (internal/process/next_tick.js:71:11)
         at process._tickCallback (internal/process/next_tick.js:98:9),
     Error: message could not be sent to electron process
         at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/checkIpcStatus.js:39:12
         at _combinedTickCallback (internal/process/next_tick.js:71:11)
         at process._tickCallback (internal/process/next_tick.js:98:9),
     Error: message could not be sent to electron process
         at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/checkIpcStatus.js:39:12
         at _combinedTickCallback (internal/process/next_tick.js:71:11)
         at process._tickCallback (internal/process/next_tick.js:98:9),
     Error: message could not be sent to electron process
         at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/checkIpcStatus.js:39:12
         at _combinedTickCallback (internal/process/next_tick.js:71:11)
         at process._tickCallback (internal/process/next_tick.js:98:9),
     Error: message could not be sent to electron process
         at /home/lambda/lambda/hotShare/urlAnalyser/node_modules/electron-workers/lib/checkIpcStatus.js:39:12
         at _combinedTickCallback (internal/process/next_tick.js:71:11)
         at process._tickCallback (internal/process/next_tick.js:98:9) ] }

**Comment by bjrmatos** [comment]
hi! seems like you don't have `electron` installed, you can install `electron` in your project with `npm install electron-prebuilt --save-dev`. if that doesn't work please give more details, what OS are you using? what is your node version?

**Comment by solderzzc** [comment]
I saw same issue on Linux but not on Mac OS X.
My linux version is Ubuntu 14.04.4 LTS. Node v4 and v6.

My packages.json is 
..
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "dependencies":{
    "coffee-script": "~1.10.0",
    "electron-workers": "~1.7.0",
    "express": "~4.14.0",
    "body-parser": "~1.0.1",
    "underscore": "1.8.3"
  },
  "devDependencies": {
    "electron-prebuilt": "^1.2.0"
  }
...

**Comment by bjrmatos** [comment]
@solderzzc thnks! i have not had the chance to test `electron-workers` in linux, another user has reported that it can't start at all. i will find the time to test in linux and fix the startup

**Comment by solderzzc** [comment]
@bjrmatos That's would be great, thanks for your outstanding job on electron-workers.

**Comment by solderzzc** [comment]
You may want to look into the startup of 'nightmare', I found they had same issue on google, but can run on my Linux for now.

https://raw.githubusercontent.com/segmentio/nightmare/master/example.js

**Comment by bjrmatos** [comment]
FYI, the details of why this package doesn't work on linux are [here](https://github.com/bjrmatos/electron-html-to/issues/87) TL;DR; electron issue in linux.

i'll wait to someone on the electron team to look at the issue, if it takes too long i will publish a workaround.

**Comment by destegabry** [comment]
Any news on this?

**Comment by bjrmatos** [comment]
@destegabry the error is because an issue in electron, see electron/electron#6868, we are waiting until that issue is resolved.

**Comment by Kerumen** [comment]
@bjrmatos I just tried today on a node docker image but I can't make it work. I use the latest version of this lib so the DISPLAY env fix is there but I still have the same error as @destegabry.
Also tried both `ipc` and `server`.
I configured my [docker image with Xvfb](https://github.com/IBM-Bluemix/docker-node-xvfb/blob/master/Dockerfile).

Do you have any clues? Thanks!

**Comment by pofider** [comment]
@Kerumen Here is the dockerfile we use in jsreportonline for this
https://github.com/jsreportonline/electron-pdf

**Comment by Kerumen** [comment]
@pofider Thanks! Got it working by running `CMD Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & export DISPLAY=:99.0 && node index.js` as you did and not in separates `RUN`s and `ENV`s instructions.

As a side question, why do you have `FROM ubuntu` and install Node.js from apt? Mine is `FROM node` and is working well.

**Comment by pofider** [comment]
@Kerumen No particular reason, just wanted to use the same base image as in other heavy images I have.

**Comment by bjrmatos** [comment]
this shouldn't be a problem anymore! it has been fixed propagating the `DISPLAY` env var to the electron process in this [line](https://github.com/bjrmatos/electron-workers/blob/master/src/ElectronWorker.js#L202)
