### ISSUE TITLE
Task Queuing Does Not Work

### ISSUE THREAD

**Issue by Akamaozu** [bjrmatos/electron-workers#155]
I sent 700 jobs at once to Electron Workers and it sent all the jobs to workers at once.
Very soon, tasks started timing out on workers.

I commented inside Electron Workers code to see what was going on.

This is what I got:

<details>
[8616:0711/080224:INFO:CONSOLE(0)] -----
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c267f80-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c2790f0-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c280620-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c285440-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c287b50-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c28c970-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c28f080-475f-11e6-8235-83b5523545d7]
 is  not busy
[8616:0711/080224:INFO:CONSOLE(0)] -----
[8616:0711/080224:INFO:CONSOLE(0)] worker [3c291790-475f-11e6-8235-83b5523545d7]
 has been choosen for the task..
[8616:0711/080224:INFO:CONSOLE(0)] -----
</details>

It looks like none of the workers appear to be busy, despite having so many jobs sent.

**Comment by bjrmatos** [comment]
@Akamaozu do you have the possibility to share your script/code? i want to debug this and compare it with your PR

**Comment by Akamaozu** [comment]
@bjrmatos made a small demo here: https://github.com/Akamaozu/electron-workers-queue-demo

The number of workers should determine the number of jobs being done concurrently. 
The default is set to the amount of CPUs you have. In my case, 4.
This means only 4 jobs should be running at the same time on my computer.

The demo queues up 100 jobs and uses setTimeout to simulate time taken to complete a job. You can tweak the amount of jobs and the duration of each job with .env file.

The demo calculates the number of jobs, the duration of each job and the amount of workers to estimate when the jobs should be done if things are being queued properly.

The formula is ( total_jobs / number_of_workers ) * job_duration.

With defaults, (100 jobs / 4 workers ) * .5 seconds  = 12.5 seconds to complete the jobs, if queued correctly.

With my patch, you'll see it get really close to the time (setTimeout is not precise). Without it, all 100 jobs will complete in less than a second, even though there is a 500 ms delay on each.

**Comment by bjrmatos** [comment]
@Akamaozu great! let me find the time to test this, your PR looks correct but i just want to play with the problem before merge it. your example is great :smile:

**Comment by bjrmatos** [comment]
a design decision i made in the beggining was to not restrict a worker to only one task per time, i think `electron` can handle heavy load, one use case for that decision is to be able to create a separate `BrowserWindow` instance in each task.

for that reason, you see all tasks finishing in less than a second because all task are launching concurrently and finishing in 500ms.

i understand that most queuing solutions work by restricting a worker to only handle one task per time, so i will add a new option to let you (and others users) choose how queuing will work for each workers. what do you think? 😄

**Comment by Akamaozu** [comment]
Choosing would be awesome since the kind of work you want workers to do will determine if multiple jobs per worker is a good or bad thing.
My job for the workers was telling me how many pages are in a PDF. 
At around 25 PDFs being checked at once, you start noticing the performance degradation in the system.
At 700 PDFs being checked, your computer is completely unusable. The cursor will not even move. Many jobs started timing out because what normally took 200 ~ 500ms was now taking over 10 seconds to complete. 
700 is just my sample amount; my program is supposed to count over 10,000 PDFs in one operation. No way I can use workers if it tries to open all of them at once.
On 13 Jul 2016 00:06, BJR Matos <notifications@github.com> wrote:a design decision i made in the beggining was to not restrict a worker to only one task per time, i think electron can handle heavy load, one use case for that decision is to be able to create a separate BrowserWindow instance in each task.

for that reason, you see all tasks finishing in less than a second because all task are launching concurrently and finishing in 500ms.

i understand that most queuing solutions work by restricting a worker to only handle one task per time, so i will add a new option to let you (and others users) choose how queuing will work for each workers. what do you think? 😄

**Comment by bjrmatos** [comment]
> 700 is just my sample amount; my program is supposed to count over 10,000 PDFs in one operation. No way I can use workers if it tries to open all of them at once.

i understand. i will make it configurable :smile: thnks for your feedback

**Comment by Akamaozu** [comment]
@bjrmatos not a problem :)

If it helps, I found [queue](https://www.npmjs.com/package/queue) library to be awesome for keeping a work queue and adjusting concurrency dynamically.

In fact, it's currently what I use on top of `electron-workers`. I only discovered your library doesn't queue when I tried to remove `queue` from my code lol.

**Comment by bjrmatos** [comment]
@Akamaozu just FYI i'm still working on this, should be done in the end of the week mostly because i don't have so much time ✋

**Comment by Akamaozu** [comment]
@bjrmatos Thanks for your hard work. You're the real electron worker hahaha

**Comment by bjrmatos** [comment]
@Akamaozu hahahaha

**Comment by bjrmatos** [comment]
finally implemented in v1.8.0 😄 

here is a gif showing the previous behaviour and the new option

![workers](https://cloud.githubusercontent.com/assets/4262050/17081372/4a920416-511b-11e6-90e7-9237d0b73628.gif)
